version: '3'
services:
  database:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - soa
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

networks:
  soa:
    external: true